Document: maemo-vision
Title: Debian maemo-vision Manual
Author: <insert document author here>
Abstract: This manual describes what maemo-vision is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/maemo-vision/maemo-vision.sgml.gz

Format: postscript
Files: /usr/share/doc/maemo-vision/maemo-vision.ps.gz

Format: text
Files: /usr/share/doc/maemo-vision/maemo-vision.text.gz

Format: HTML
Index: /usr/share/doc/maemo-vision/html/index.html
Files: /usr/share/doc/maemo-vision/html/*.html


