######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 7 01:19:33 2009
######################################################################

TEMPLATE = app
TARGET = example7
INCLUDEPATH += ../../include

CONFIG += debug warn_on

HEADERS += OverlayWidget.h CameraThread.h
SOURCES += example7.cpp OverlayWidget.cpp CameraThread.cpp

CONFIG += qt 
LIBS += -lpthread -L../.. -ljpeg -lFCam

