Document: example7
Title: Debian example7 Manual
Author: <insert document author here>
Abstract: This manual describes what example7 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/example7/example7.sgml.gz

Format: postscript
Files: /usr/share/doc/example7/example7.ps.gz

Format: text
Files: /usr/share/doc/example7/example7.text.gz

Format: HTML
Index: /usr/share/doc/example7/html/index.html
Files: /usr/share/doc/example7/html/*.html


